// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/internal/recommendations/external/recbole": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "获取 RecBole 召回视频片段ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回的视频片段ID数量，最多500个",
                        "name": "n",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询题目列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.QuestionListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/questions/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询题目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "题目ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.QuestionDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/recommendations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询推荐列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "题目ID",
                        "name": "question_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RecommendationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/recommendations/by-question": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "根据题目推荐视频",
                "parameters": [
                    {
                        "description": "推荐请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RecommendByQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RecommendationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/transcode-tasks/{taskId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询转码任务状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "转码任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TranscodeStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/video-segments/random-play": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "随机播放视频片段",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID，用于个性化推荐和最近播放去重",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RandomVideoSegmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/video-segments/{id}/reaction-counts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询视频片段点赞和双击数量",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频片段ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SegmentReactionCountsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/video-segments/{id}/reactions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "提交或取消视频片段互动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频片段ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "互动参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VideoReactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SegmentReactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询视频列表",
                "parameters": [
                    {
                        "enum": [
                            "ALL",
                            "RAW",
                            "HLS"
                        ],
                        "type": "string",
                        "default": "ALL",
                        "description": "视频类型筛选",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VideoListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "上传单个视频",
                "parameters": [
                    {
                        "type": "file",
                        "description": "视频文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "视频标题",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "视频描述",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "上传用户ID，默认1",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/archive": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "上传视频压缩包",
                "parameters": [
                    {
                        "type": "file",
                        "description": "视频压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "视频描述",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "上传用户ID，默认1",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadVideoArchiveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/archive/batches/{batchId}/progress": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询视频压缩包处理进度",
                "parameters": [
                    {
                        "type": "string",
                        "description": "压缩包批次ID",
                        "name": "batchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ArchiveProcessingProgressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/archive/uploads": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "初始化视频压缩包分片上传",
                "parameters": [
                    {
                        "description": "压缩包分片上传元信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InitiateChunkedUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ChunkedUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/archive/uploads/{uploadId}/complete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "完成视频压缩包分片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传任务ID",
                        "name": "uploadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadVideoArchiveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/uploads": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "初始化视频分片上传",
                "parameters": [
                    {
                        "description": "分片上传元信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InitiateChunkedUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ChunkedUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/uploads/{uploadId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询视频分片上传状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传任务ID",
                        "name": "uploadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ChunkedUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/uploads/{uploadId}/chunks/{chunkIndex}": {
            "put": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "上传视频分片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传任务ID",
                        "name": "uploadId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分片序号，从0开始",
                        "name": "chunkIndex",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分片二进制内容",
                        "name": "chunk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ChunkedUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/uploads/{uploadId}/complete": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "完成视频分片上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传任务ID",
                        "name": "uploadId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "删除视频",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "修改视频基础信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "视频基础信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVideoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/cover": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "上传视频封面",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "封面文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadCoverResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/play": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "获取视频播放地址",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PlayVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "设置视频发布状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "发布状态参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PublishVideoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PublishVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/reaction-counts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询视频点赞和双击数量",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VideoReactionCountsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/reactions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "提交或取消视频互动",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "互动参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VideoReactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.VideoReactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/recommend": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "设置视频推荐状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "推荐状态参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RecommendVideoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RecommendVideoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/similar": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询相似视频",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "返回数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SimilarVideosResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/videos/{id}/view-count": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "查询视频播放次数",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "视频ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ViewCountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/watch-records": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频服务"
                ],
                "summary": "上报视频观看进度",
                "parameters": [
                    {
                        "description": "观看进度参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReportWatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.WatchRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ArchiveProcessingProgressData": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "transcoded": {
                    "type": "integer"
                },
                "vectorized": {
                    "type": "integer"
                }
            }
        },
        "dto.ArchiveProcessingProgressResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ArchiveProcessingProgressData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.ChunkedUploadData": {
            "type": "object",
            "properties": {
                "chunk_size": {
                    "type": "integer"
                },
                "completed": {
                    "type": "boolean"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "total_chunks": {
                    "type": "integer"
                },
                "upload_id": {
                    "type": "string"
                },
                "uploaded_chunks": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.ChunkedUploadResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ChunkedUploadData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.DeleteVideoData": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.DeleteVideoData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/dto.ErrorBody"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.InitiateChunkedUploadRequest": {
            "type": "object",
            "properties": {
                "chunk_size": {
                    "type": "integer"
                },
                "content_type": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "total_chunks": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PlayVideoData": {
            "type": "object",
            "properties": {
                "play_url": {
                    "type": "string"
                },
                "video": {
                    "$ref": "#/definitions/dto.VideoItem"
                }
            }
        },
        "dto.PlayVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.PlayVideoData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.PublishVideoData": {
            "type": "object",
            "properties": {
                "is_published": {
                    "type": "boolean"
                },
                "updated": {
                    "type": "boolean"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.PublishVideoRequest": {
            "type": "object",
            "properties": {
                "is_published": {
                    "type": "boolean"
                }
            }
        },
        "dto.PublishVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.PublishVideoData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.QuestionDetailData": {
            "type": "object",
            "properties": {
                "question": {
                    "$ref": "#/definitions/dto.QuestionItem"
                }
            }
        },
        "dto.QuestionDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.QuestionDetailData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.QuestionItem": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "string"
                },
                "answer": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "create_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "knowledge": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "source_question_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "subject": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "dto.QuestionListData": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.QuestionItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.QuestionListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.QuestionListData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.RandomVideoSegmentData": {
            "type": "object",
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "end_time_sec": {
                    "type": "integer"
                },
                "play_url": {
                    "type": "string"
                },
                "start_time_sec": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "user_reacted": {
                    "type": "boolean"
                },
                "user_reaction_type": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                },
                "video_segment_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RandomVideoSegmentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RandomVideoSegmentData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.RecommendByQuestionRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "question_id": {
                    "type": "integer"
                },
                "question_text": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RecommendVideoData": {
            "type": "object",
            "properties": {
                "is_recommend": {
                    "type": "boolean"
                },
                "updated": {
                    "type": "boolean"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RecommendVideoRequest": {
            "type": "object",
            "properties": {
                "is_recommend": {
                    "type": "boolean"
                },
                "recommend_level": {
                    "type": "integer"
                },
                "recommend_score": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.RecommendVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RecommendVideoData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.RecommendationItem": {
            "type": "object",
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "end_time_sec": {
                    "type": "integer"
                },
                "is_watched": {
                    "type": "boolean"
                },
                "play_url": {
                    "type": "string"
                },
                "question_id": {
                    "type": "integer"
                },
                "recommend_score": {
                    "type": "number"
                },
                "start_time_sec": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                },
                "video_segment_id": {
                    "type": "integer"
                },
                "watch_duration": {
                    "type": "integer"
                }
            }
        },
        "dto.RecommendationListData": {
            "type": "object",
            "properties": {
                "degraded": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RecommendationItem"
                    }
                },
                "message": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.RecommendationListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RecommendationListData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.ReportWatchRequest": {
            "type": "object",
            "properties": {
                "is_watched": {
                    "type": "boolean"
                },
                "question_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "video_segment_id": {
                    "type": "integer"
                },
                "watch_duration": {
                    "type": "integer"
                }
            }
        },
        "dto.SegmentReactionCountsData": {
            "type": "object",
            "properties": {
                "double_like_count": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "segment_id": {
                    "type": "integer"
                }
            }
        },
        "dto.SegmentReactionCountsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SegmentReactionCountsData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.SegmentReactionData": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "double_like_count": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "reaction_type": {
                    "type": "string"
                },
                "segment_id": {
                    "type": "integer"
                },
                "updated": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.SegmentReactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SegmentReactionData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.SimilarVideosData": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VideoItem"
                    }
                }
            }
        },
        "dto.SimilarVideosResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SimilarVideosData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.TranscodeStatusData": {
            "type": "object",
            "properties": {
                "hls_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "dto.TranscodeStatusResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.TranscodeStatusData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateVideoData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated": {
                    "type": "boolean"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateVideoRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 5000
                },
                "title": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "dto.UpdateVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UpdateVideoData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UploadArchiveError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                }
            }
        },
        "dto.UploadCoverData": {
            "type": "object",
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UploadCoverResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UploadCoverData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UploadVideoArchiveData": {
            "type": "object",
            "properties": {
                "batch_id": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UploadArchiveError"
                    }
                },
                "failed": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "skipped_files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                },
                "uploaded": {
                    "type": "integer"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UploadVideoData"
                    }
                }
            }
        },
        "dto.UploadVideoArchiveResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UploadVideoArchiveData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UploadVideoData": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "hls_url": {
                    "type": "string"
                },
                "raw_url": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.UploadVideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UploadVideoData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.VideoItem": {
            "type": "object",
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "created_at_unix": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "hls_url": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "is_recommend": {
                    "type": "boolean"
                },
                "raw_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at_unix": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                },
                "view_count": {
                    "type": "integer"
                }
            }
        },
        "dto.VideoListData": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.VideoItem"
                    }
                }
            }
        },
        "dto.VideoListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.VideoListData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.VideoReactionCountsData": {
            "type": "object",
            "properties": {
                "double_like_count": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.VideoReactionCountsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.VideoReactionCountsData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.VideoReactionData": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "double_like_count": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "reaction_type": {
                    "type": "string"
                },
                "updated": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "integer"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "dto.VideoReactionRequest": {
            "type": "object",
            "properties": {
                "reaction_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "dto.VideoReactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.VideoReactionData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.ViewCountData": {
            "type": "object",
            "properties": {
                "video_id": {
                    "type": "integer"
                },
                "view_count": {
                    "type": "integer"
                }
            }
        },
        "dto.ViewCountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ViewCountData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.WatchRecordData": {
            "type": "object",
            "properties": {
                "recorded": {
                    "type": "boolean"
                }
            }
        },
        "dto.WatchRecordResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.WatchRecordData"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "衡水平板视频服务接口",
	Description:      "提供视频上传、播放、推荐、题目查询等 HTTP 接口。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
