// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: video/video_service.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoType int32

const (
	VideoType_ALL VideoType = 0
	VideoType_RAW VideoType = 1
	VideoType_HLS VideoType = 2
)

// Enum value maps for VideoType.
var (
	VideoType_name = map[int32]string{
		0: "ALL",
		1: "RAW",
		2: "HLS",
	}
	VideoType_value = map[string]int32{
		"ALL": 0,
		"RAW": 1,
		"HLS": 2,
	}
)

func (x VideoType) Enum() *VideoType {
	p := new(VideoType)
	*p = x
	return p
}

func (x VideoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_service_proto_enumTypes[0].Descriptor()
}

func (VideoType) Type() protoreflect.EnumType {
	return &file_video_video_service_proto_enumTypes[0]
}

func (x VideoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoType.Descriptor instead.
func (VideoType) EnumDescriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{0}
}

type TranscodeStatus int32

const (
	TranscodeStatus_PENDING    TranscodeStatus = 0
	TranscodeStatus_PROCESSING TranscodeStatus = 1
	TranscodeStatus_SUCCESS    TranscodeStatus = 2
	TranscodeStatus_FAILED     TranscodeStatus = 3
)

// Enum value maps for TranscodeStatus.
var (
	TranscodeStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROCESSING",
		2: "SUCCESS",
		3: "FAILED",
	}
	TranscodeStatus_value = map[string]int32{
		"PENDING":    0,
		"PROCESSING": 1,
		"SUCCESS":    2,
		"FAILED":     3,
	}
)

func (x TranscodeStatus) Enum() *TranscodeStatus {
	p := new(TranscodeStatus)
	*p = x
	return p
}

func (x TranscodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_video_video_service_proto_enumTypes[1].Descriptor()
}

func (TranscodeStatus) Type() protoreflect.EnumType {
	return &file_video_video_service_proto_enumTypes[1]
}

func (x TranscodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscodeStatus.Descriptor instead.
func (TranscodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{1}
}

// 上传视频请求（流式）
type UploadVideoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadVideoRequest_Meta
	//	*UploadVideoRequest_ChunkData
	Data          isUploadVideoRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_video_video_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadVideoRequest) GetData() isUploadVideoRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadVideoRequest) GetMeta() *VideoMeta {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadVideoRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadVideoRequest_Data interface {
	isUploadVideoRequest_Data()
}

type UploadVideoRequest_Meta struct {
	Meta *VideoMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadVideoRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadVideoRequest_Meta) isUploadVideoRequest_Data() {}

func (*UploadVideoRequest_ChunkData) isUploadVideoRequest_Data() {}

type VideoMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMeta) Reset() {
	*x = VideoMeta{}
	mi := &file_video_video_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMeta) ProtoMessage() {}

func (x *VideoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMeta.ProtoReflect.Descriptor instead.
func (*VideoMeta) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{1}
}

func (x *VideoMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *VideoMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *VideoMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UploadVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	RawUrl        string                 `protobuf:"bytes,4,opt,name=raw_url,json=rawUrl,proto3" json:"raw_url,omitempty"`
	HlsUrl        string                 `protobuf:"bytes,5,opt,name=hls_url,json=hlsUrl,proto3" json:"hls_url,omitempty"`
	TaskId        string                 `protobuf:"bytes,6,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	VideoId       uint64                 `protobuf:"varint,7,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResponse) Reset() {
	*x = UploadVideoResponse{}
	mi := &file_video_video_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResponse) ProtoMessage() {}

func (x *UploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResponse.ProtoReflect.Descriptor instead.
func (*UploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadVideoResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadVideoResponse) GetRawUrl() string {
	if x != nil {
		return x.RawUrl
	}
	return ""
}

func (x *UploadVideoResponse) GetHlsUrl() string {
	if x != nil {
		return x.HlsUrl
	}
	return ""
}

func (x *UploadVideoResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UploadVideoResponse) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 视频列表
type ListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterType    VideoType              `protobuf:"varint,1,opt,name=filter_type,json=filterType,proto3,enum=video.VideoType" json:"filter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_video_video_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListVideosRequest) GetFilterType() VideoType {
	if x != nil {
		return x.FilterType
	}
	return VideoType_ALL
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RawUrl        string                 `protobuf:"bytes,2,opt,name=raw_url,json=rawUrl,proto3" json:"raw_url,omitempty"`
	HlsUrl        string                 `protobuf:"bytes,3,opt,name=hls_url,json=hlsUrl,proto3" json:"hls_url,omitempty"`
	IsHls         bool                   `protobuf:"varint,4,opt,name=is_hls,json=isHls,proto3" json:"is_hls,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	TaskId        string                 `protobuf:"bytes,6,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Id            uint64                 `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	ViewCount     int64                  `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	IsPublished   bool                   `protobuf:"varint,9,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	IsRecommend   bool                   `protobuf:"varint,10,opt,name=is_recommend,json=isRecommend,proto3" json:"is_recommend,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,11,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,12,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,13,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Title         string                 `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_video_video_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{4}
}

func (x *VideoInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VideoInfo) GetRawUrl() string {
	if x != nil {
		return x.RawUrl
	}
	return ""
}

func (x *VideoInfo) GetHlsUrl() string {
	if x != nil {
		return x.HlsUrl
	}
	return ""
}

func (x *VideoInfo) GetIsHls() bool {
	if x != nil {
		return x.IsHls
	}
	return false
}

func (x *VideoInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *VideoInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *VideoInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *VideoInfo) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *VideoInfo) GetIsRecommend() bool {
	if x != nil {
		return x.IsRecommend
	}
	return false
}

func (x *VideoInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *VideoInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResponse) Reset() {
	*x = ListVideosResponse{}
	mi := &file_video_video_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResponse) ProtoMessage() {}

func (x *ListVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListVideosResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateVideoMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoMetadataRequest) Reset() {
	*x = UpdateVideoMetadataRequest{}
	mi := &file_video_video_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoMetadataRequest) ProtoMessage() {}

func (x *UpdateVideoMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoMetadataRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVideoMetadataRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UpdateVideoMetadataRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoMetadataRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateVideoMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoMetadataResponse) Reset() {
	*x = UpdateVideoMetadataResponse{}
	mi := &file_video_video_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoMetadataResponse) ProtoMessage() {}

func (x *UpdateVideoMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoMetadataResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVideoMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVideoMetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateVideoMetadataResponse) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UpdateVideoMetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoMetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 删除视频
type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_video_video_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVideoRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DeleteVideoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_video_video_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 播放视频（服务端可用于 view_count + 1）
type PlayVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayVideoRequest) Reset() {
	*x = PlayVideoRequest{}
	mi := &file_video_video_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayVideoRequest) ProtoMessage() {}

func (x *PlayVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayVideoRequest.ProtoReflect.Descriptor instead.
func (*PlayVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{10}
}

func (x *PlayVideoRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *PlayVideoRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type PlayVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayUrl       string                 `protobuf:"bytes,1,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	Video         *VideoInfo             `protobuf:"bytes,2,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayVideoResponse) Reset() {
	*x = PlayVideoResponse{}
	mi := &file_video_video_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayVideoResponse) ProtoMessage() {}

func (x *PlayVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayVideoResponse.ProtoReflect.Descriptor instead.
func (*PlayVideoResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{11}
}

func (x *PlayVideoResponse) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *PlayVideoResponse) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

// 相近视频
type GetSimilarVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarVideosRequest) Reset() {
	*x = GetSimilarVideosRequest{}
	mi := &file_video_video_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarVideosRequest) ProtoMessage() {}

func (x *GetSimilarVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarVideosRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetSimilarVideosRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetSimilarVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSimilarVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarVideosResponse) Reset() {
	*x = GetSimilarVideosResponse{}
	mi := &file_video_video_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarVideosResponse) ProtoMessage() {}

func (x *GetSimilarVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarVideosResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarVideosResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetSimilarVideosResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetSimilarVideosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查看观看次数
type GetViewCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewCountRequest) Reset() {
	*x = GetViewCountRequest{}
	mi := &file_video_video_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewCountRequest) ProtoMessage() {}

func (x *GetViewCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewCountRequest.ProtoReflect.Descriptor instead.
func (*GetViewCountRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetViewCountRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetViewCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ViewCount     int64                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewCountResponse) Reset() {
	*x = GetViewCountResponse{}
	mi := &file_video_video_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewCountResponse) ProtoMessage() {}

func (x *GetViewCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewCountResponse.ProtoReflect.Descriptor instead.
func (*GetViewCountResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetViewCountResponse) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetViewCountResponse) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

// 推荐池列表
type ListRecommendPoolVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendPoolVideosRequest) Reset() {
	*x = ListRecommendPoolVideosRequest{}
	mi := &file_video_video_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendPoolVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendPoolVideosRequest) ProtoMessage() {}

func (x *ListRecommendPoolVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendPoolVideosRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendPoolVideosRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{16}
}

// 发布视频
type SetVideoPublishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,2,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVideoPublishedRequest) Reset() {
	*x = SetVideoPublishedRequest{}
	mi := &file_video_video_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVideoPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoPublishedRequest) ProtoMessage() {}

func (x *SetVideoPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoPublishedRequest.ProtoReflect.Descriptor instead.
func (*SetVideoPublishedRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{17}
}

func (x *SetVideoPublishedRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SetVideoPublishedRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type SetVideoPublishedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,4,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVideoPublishedResponse) Reset() {
	*x = SetVideoPublishedResponse{}
	mi := &file_video_video_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVideoPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoPublishedResponse) ProtoMessage() {}

func (x *SetVideoPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoPublishedResponse.ProtoReflect.Descriptor instead.
func (*SetVideoPublishedResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{18}
}

func (x *SetVideoPublishedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetVideoPublishedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetVideoPublishedResponse) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SetVideoPublishedResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

// 加入/移出推荐池
type SetVideoRecommendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VideoId        uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	IsRecommend    bool                   `protobuf:"varint,2,opt,name=is_recommend,json=isRecommend,proto3" json:"is_recommend,omitempty"`
	UserId         uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecommendLevel int32                  `protobuf:"varint,4,opt,name=recommend_level,json=recommendLevel,proto3" json:"recommend_level,omitempty"`
	RecommendScore float64                `protobuf:"fixed64,5,opt,name=recommend_score,json=recommendScore,proto3" json:"recommend_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetVideoRecommendRequest) Reset() {
	*x = SetVideoRecommendRequest{}
	mi := &file_video_video_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVideoRecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoRecommendRequest) ProtoMessage() {}

func (x *SetVideoRecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoRecommendRequest.ProtoReflect.Descriptor instead.
func (*SetVideoRecommendRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{19}
}

func (x *SetVideoRecommendRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SetVideoRecommendRequest) GetIsRecommend() bool {
	if x != nil {
		return x.IsRecommend
	}
	return false
}

func (x *SetVideoRecommendRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetVideoRecommendRequest) GetRecommendLevel() int32 {
	if x != nil {
		return x.RecommendLevel
	}
	return 0
}

func (x *SetVideoRecommendRequest) GetRecommendScore() float64 {
	if x != nil {
		return x.RecommendScore
	}
	return 0
}

type SetVideoRecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	IsRecommend   bool                   `protobuf:"varint,4,opt,name=is_recommend,json=isRecommend,proto3" json:"is_recommend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVideoRecommendResponse) Reset() {
	*x = SetVideoRecommendResponse{}
	mi := &file_video_video_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVideoRecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoRecommendResponse) ProtoMessage() {}

func (x *SetVideoRecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoRecommendResponse.ProtoReflect.Descriptor instead.
func (*SetVideoRecommendResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{20}
}

func (x *SetVideoRecommendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetVideoRecommendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetVideoRecommendResponse) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SetVideoRecommendResponse) GetIsRecommend() bool {
	if x != nil {
		return x.IsRecommend
	}
	return false
}

// 设置视频封面（由 API 上传到对象存储后，调用此接口写入 cover_url）
type SetVideoCoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       uint64                 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,2,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVideoCoverRequest) Reset() {
	*x = SetVideoCoverRequest{}
	mi := &file_video_video_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVideoCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoCoverRequest) ProtoMessage() {}

func (x *SetVideoCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoCoverRequest.ProtoReflect.Descriptor instead.
func (*SetVideoCoverRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{21}
}

func (x *SetVideoCoverRequest) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SetVideoCoverRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type SetVideoCoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoId       uint64                 `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVideoCoverResponse) Reset() {
	*x = SetVideoCoverResponse{}
	mi := &file_video_video_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVideoCoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoCoverResponse) ProtoMessage() {}

func (x *SetVideoCoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoCoverResponse.ProtoReflect.Descriptor instead.
func (*SetVideoCoverResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{22}
}

func (x *SetVideoCoverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetVideoCoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetVideoCoverResponse) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *SetVideoCoverResponse) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

// 转码状态
type GetTranscodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscodeStatusRequest) Reset() {
	*x = GetTranscodeStatusRequest{}
	mi := &file_video_video_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscodeStatusRequest) ProtoMessage() {}

func (x *GetTranscodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTranscodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetTranscodeStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTranscodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TranscodeStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=video.TranscodeStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	HlsUrl        string                 `protobuf:"bytes,4,opt,name=hls_url,json=hlsUrl,proto3" json:"hls_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscodeStatusResponse) Reset() {
	*x = GetTranscodeStatusResponse{}
	mi := &file_video_video_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscodeStatusResponse) ProtoMessage() {}

func (x *GetTranscodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscodeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTranscodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetTranscodeStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTranscodeStatusResponse) GetStatus() TranscodeStatus {
	if x != nil {
		return x.Status
	}
	return TranscodeStatus_PENDING
}

func (x *GetTranscodeStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTranscodeStatusResponse) GetHlsUrl() string {
	if x != nil {
		return x.HlsUrl
	}
	return ""
}

type RecommendByQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	QuestionText  string                 `protobuf:"bytes,2,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendByQuestionRequest) Reset() {
	*x = RecommendByQuestionRequest{}
	mi := &file_video_video_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendByQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendByQuestionRequest) ProtoMessage() {}

func (x *RecommendByQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendByQuestionRequest.ProtoReflect.Descriptor instead.
func (*RecommendByQuestionRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{25}
}

func (x *RecommendByQuestionRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *RecommendByQuestionRequest) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *RecommendByQuestionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecommendByQuestionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecommendItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuestionId     uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	VideoId        uint64                 `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoSegmentId uint64                 `protobuf:"varint,3,opt,name=video_segment_id,json=videoSegmentId,proto3" json:"video_segment_id,omitempty"`
	RecommendScore float64                `protobuf:"fixed64,4,opt,name=recommend_score,json=recommendScore,proto3" json:"recommend_score,omitempty"`
	IsWatched      bool                   `protobuf:"varint,5,opt,name=is_watched,json=isWatched,proto3" json:"is_watched,omitempty"`
	WatchDuration  int32                  `protobuf:"varint,6,opt,name=watch_duration,json=watchDuration,proto3" json:"watch_duration,omitempty"`
	Video          *VideoInfo             `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	StartTimeSec   int32                  `protobuf:"varint,8,opt,name=start_time_sec,json=startTimeSec,proto3" json:"start_time_sec,omitempty"`
	EndTimeSec     int32                  `protobuf:"varint,9,opt,name=end_time_sec,json=endTimeSec,proto3" json:"end_time_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecommendItem) Reset() {
	*x = RecommendItem{}
	mi := &file_video_video_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendItem) ProtoMessage() {}

func (x *RecommendItem) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendItem.ProtoReflect.Descriptor instead.
func (*RecommendItem) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{26}
}

func (x *RecommendItem) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *RecommendItem) GetVideoId() uint64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *RecommendItem) GetVideoSegmentId() uint64 {
	if x != nil {
		return x.VideoSegmentId
	}
	return 0
}

func (x *RecommendItem) GetRecommendScore() float64 {
	if x != nil {
		return x.RecommendScore
	}
	return 0
}

func (x *RecommendItem) GetIsWatched() bool {
	if x != nil {
		return x.IsWatched
	}
	return false
}

func (x *RecommendItem) GetWatchDuration() int32 {
	if x != nil {
		return x.WatchDuration
	}
	return 0
}

func (x *RecommendItem) GetVideo() *VideoInfo {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *RecommendItem) GetStartTimeSec() int32 {
	if x != nil {
		return x.StartTimeSec
	}
	return 0
}

func (x *RecommendItem) GetEndTimeSec() int32 {
	if x != nil {
		return x.EndTimeSec
	}
	return 0
}

type RecommendByQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecommendItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendByQuestionResponse) Reset() {
	*x = RecommendByQuestionResponse{}
	mi := &file_video_video_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendByQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendByQuestionResponse) ProtoMessage() {}

func (x *RecommendByQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendByQuestionResponse.ProtoReflect.Descriptor instead.
func (*RecommendByQuestionResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{27}
}

func (x *RecommendByQuestionResponse) GetItems() []*RecommendItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendByQuestionResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsRequest) Reset() {
	*x = ListRecommendationsRequest{}
	mi := &file_video_video_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsRequest) ProtoMessage() {}

func (x *ListRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{28}
}

func (x *ListRecommendationsRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *ListRecommendationsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecommendItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsResponse) Reset() {
	*x = ListRecommendationsResponse{}
	mi := &file_video_video_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsResponse) ProtoMessage() {}

func (x *ListRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*ListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListRecommendationsResponse) GetItems() []*RecommendItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRecommendationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReportWatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuestionId     uint64                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId         uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoSegmentId uint64                 `protobuf:"varint,3,opt,name=video_segment_id,json=videoSegmentId,proto3" json:"video_segment_id,omitempty"`
	IsWatched      bool                   `protobuf:"varint,4,opt,name=is_watched,json=isWatched,proto3" json:"is_watched,omitempty"`
	WatchDuration  int32                  `protobuf:"varint,5,opt,name=watch_duration,json=watchDuration,proto3" json:"watch_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportWatchRequest) Reset() {
	*x = ReportWatchRequest{}
	mi := &file_video_video_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportWatchRequest) ProtoMessage() {}

func (x *ReportWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportWatchRequest.ProtoReflect.Descriptor instead.
func (*ReportWatchRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{30}
}

func (x *ReportWatchRequest) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *ReportWatchRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportWatchRequest) GetVideoSegmentId() uint64 {
	if x != nil {
		return x.VideoSegmentId
	}
	return 0
}

func (x *ReportWatchRequest) GetIsWatched() bool {
	if x != nil {
		return x.IsWatched
	}
	return false
}

func (x *ReportWatchRequest) GetWatchDuration() int32 {
	if x != nil {
		return x.WatchDuration
	}
	return 0
}

type ReportWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportWatchResponse) Reset() {
	*x = ReportWatchResponse{}
	mi := &file_video_video_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportWatchResponse) ProtoMessage() {}

func (x *ReportWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportWatchResponse.ProtoReflect.Descriptor instead.
func (*ReportWatchResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{31}
}

func (x *ReportWatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportWatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_video_video_service_proto protoreflect.FileDescriptor

const file_video_video_service_proto_rawDesc = "" +
	"\n" +
	"\x19video/video_service.proto\x12\x05video\"e\n" +
	"\x12UploadVideoRequest\x12&\n" +
	"\x04meta\x18\x01 \x01(\v2\x10.video.VideoMetaH\x00R\x04meta\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"\x83\x01\n" +
	"\tVideoMeta\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xcc\x01\n" +
	"\x13UploadVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x17\n" +
	"\araw_url\x18\x04 \x01(\tR\x06rawUrl\x12\x17\n" +
	"\ahls_url\x18\x05 \x01(\tR\x06hlsUrl\x12\x17\n" +
	"\atask_id\x18\x06 \x01(\tR\x06taskId\x12\x19\n" +
	"\bvideo_id\x18\a \x01(\x04R\avideoId\"F\n" +
	"\x11ListVideosRequest\x121\n" +
	"\vfilter_type\x18\x01 \x01(\x0e2\x10.video.VideoTypeR\n" +
	"filterType\"\xbe\x03\n" +
	"\tVideoInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\araw_url\x18\x02 \x01(\tR\x06rawUrl\x12\x17\n" +
	"\ahls_url\x18\x03 \x01(\tR\x06hlsUrl\x12\x15\n" +
	"\x06is_hls\x18\x04 \x01(\bR\x05isHls\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrl\x12\x17\n" +
	"\atask_id\x18\x06 \x01(\tR\x06taskId\x12\x0e\n" +
	"\x02id\x18\a \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\x03R\tviewCount\x12!\n" +
	"\fis_published\x18\t \x01(\bR\visPublished\x12!\n" +
	"\fis_recommend\x18\n" +
	" \x01(\bR\visRecommend\x12&\n" +
	"\x0fcreated_at_unix\x18\v \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\f \x01(\x03R\rupdatedAtUnix\x12\x1b\n" +
	"\tcover_url\x18\r \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05title\x18\x0e \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\"T\n" +
	"\x12ListVideosResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"o\n" +
	"\x1aUpdateVideoMetadataRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa4\x01\n" +
	"\x1bUpdateVideoMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"H\n" +
	"\x12DeleteVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"I\n" +
	"\x13DeleteVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x10PlayVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"V\n" +
	"\x11PlayVideoResponse\x12\x19\n" +
	"\bplay_url\x18\x01 \x01(\tR\aplayUrl\x12&\n" +
	"\x05video\x18\x02 \x01(\v2\x10.video.VideoInfoR\x05video\"J\n" +
	"\x17GetSimilarVideosRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Z\n" +
	"\x18GetSimilarVideosResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"0\n" +
	"\x13GetViewCountRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\"P\n" +
	"\x14GetViewCountResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x03R\tviewCount\" \n" +
	"\x1eListRecommendPoolVideosRequest\"X\n" +
	"\x18SetVideoPublishedRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12!\n" +
	"\fis_published\x18\x02 \x01(\bR\visPublished\"\x8d\x01\n" +
	"\x19SetVideoPublishedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12!\n" +
	"\fis_published\x18\x04 \x01(\bR\visPublished\"\xc3\x01\n" +
	"\x18SetVideoRecommendRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12!\n" +
	"\fis_recommend\x18\x02 \x01(\bR\visRecommend\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12'\n" +
	"\x0frecommend_level\x18\x04 \x01(\x05R\x0erecommendLevel\x12'\n" +
	"\x0frecommend_score\x18\x05 \x01(\x01R\x0erecommendScore\"\x8d\x01\n" +
	"\x19SetVideoRecommendResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12!\n" +
	"\fis_recommend\x18\x04 \x01(\bR\visRecommend\"N\n" +
	"\x14SetVideoCoverRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x04R\avideoId\x12\x1b\n" +
	"\tcover_url\x18\x02 \x01(\tR\bcoverUrl\"\x83\x01\n" +
	"\x15SetVideoCoverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x04R\avideoId\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\"4\n" +
	"\x19GetTranscodeStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x98\x01\n" +
	"\x1aGetTranscodeStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.video.TranscodeStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\ahls_url\x18\x04 \x01(\tR\x06hlsUrl\"\x91\x01\n" +
	"\x1aRecommendByQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12#\n" +
	"\rquestion_text\x18\x02 \x01(\tR\fquestionText\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xd4\x02\n" +
	"\rRecommendItem\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x04R\avideoId\x12(\n" +
	"\x10video_segment_id\x18\x03 \x01(\x04R\x0evideoSegmentId\x12'\n" +
	"\x0frecommend_score\x18\x04 \x01(\x01R\x0erecommendScore\x12\x1d\n" +
	"\n" +
	"is_watched\x18\x05 \x01(\bR\tisWatched\x12%\n" +
	"\x0ewatch_duration\x18\x06 \x01(\x05R\rwatchDuration\x12&\n" +
	"\x05video\x18\a \x01(\v2\x10.video.VideoInfoR\x05video\x12$\n" +
	"\x0estart_time_sec\x18\b \x01(\x05R\fstartTimeSec\x12 \n" +
	"\fend_time_sec\x18\t \x01(\x05R\n" +
	"endTimeSec\"_\n" +
	"\x1bRecommendByQuestionResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.video.RecommendItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"l\n" +
	"\x1aListRecommendationsRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"_\n" +
	"\x1bListRecommendationsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.video.RecommendItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xbe\x01\n" +
	"\x12ReportWatchRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12(\n" +
	"\x10video_segment_id\x18\x03 \x01(\x04R\x0evideoSegmentId\x12\x1d\n" +
	"\n" +
	"is_watched\x18\x04 \x01(\bR\tisWatched\x12%\n" +
	"\x0ewatch_duration\x18\x05 \x01(\x05R\rwatchDuration\"I\n" +
	"\x13ReportWatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*&\n" +
	"\tVideoType\x12\a\n" +
	"\x03ALL\x10\x00\x12\a\n" +
	"\x03RAW\x10\x01\x12\a\n" +
	"\x03HLS\x10\x02*G\n" +
	"\x0fTranscodeStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\xd1\t\n" +
	"\fVideoService\x12F\n" +
	"\vUploadVideo\x12\x19.video.UploadVideoRequest\x1a\x1a.video.UploadVideoResponse(\x01\x12A\n" +
	"\n" +
	"ListVideos\x12\x18.video.ListVideosRequest\x1a\x19.video.ListVideosResponse\x12\\\n" +
	"\x13UpdateVideoMetadata\x12!.video.UpdateVideoMetadataRequest\x1a\".video.UpdateVideoMetadataResponse\x12D\n" +
	"\vDeleteVideo\x12\x19.video.DeleteVideoRequest\x1a\x1a.video.DeleteVideoResponse\x12>\n" +
	"\tPlayVideo\x12\x17.video.PlayVideoRequest\x1a\x18.video.PlayVideoResponse\x12S\n" +
	"\x10GetSimilarVideos\x12\x1e.video.GetSimilarVideosRequest\x1a\x1f.video.GetSimilarVideosResponse\x12G\n" +
	"\fGetViewCount\x12\x1a.video.GetViewCountRequest\x1a\x1b.video.GetViewCountResponse\x12[\n" +
	"\x17ListRecommendPoolVideos\x12%.video.ListRecommendPoolVideosRequest\x1a\x19.video.ListVideosResponse\x12V\n" +
	"\x11SetVideoPublished\x12\x1f.video.SetVideoPublishedRequest\x1a .video.SetVideoPublishedResponse\x12V\n" +
	"\x11SetVideoRecommend\x12\x1f.video.SetVideoRecommendRequest\x1a .video.SetVideoRecommendResponse\x12J\n" +
	"\rSetVideoCover\x12\x1b.video.SetVideoCoverRequest\x1a\x1c.video.SetVideoCoverResponse\x12Y\n" +
	"\x12GetTranscodeStatus\x12 .video.GetTranscodeStatusRequest\x1a!.video.GetTranscodeStatusResponse\x12\\\n" +
	"\x13RecommendByQuestion\x12!.video.RecommendByQuestionRequest\x1a\".video.RecommendByQuestionResponse\x12\\\n" +
	"\x13ListRecommendations\x12!.video.ListRecommendationsRequest\x1a\".video.ListRecommendationsResponse\x12D\n" +
	"\vReportWatch\x12\x19.video.ReportWatchRequest\x1a\x1a.video.ReportWatchResponseB\x0fZ\r./video;videob\x06proto3"

var (
	file_video_video_service_proto_rawDescOnce sync.Once
	file_video_video_service_proto_rawDescData []byte
)

func file_video_video_service_proto_rawDescGZIP() []byte {
	file_video_video_service_proto_rawDescOnce.Do(func() {
		file_video_video_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_video_service_proto_rawDesc), len(file_video_video_service_proto_rawDesc)))
	})
	return file_video_video_service_proto_rawDescData
}

var file_video_video_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_video_video_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_video_video_service_proto_goTypes = []any{
	(VideoType)(0),                         // 0: video.VideoType
	(TranscodeStatus)(0),                   // 1: video.TranscodeStatus
	(*UploadVideoRequest)(nil),             // 2: video.UploadVideoRequest
	(*VideoMeta)(nil),                      // 3: video.VideoMeta
	(*UploadVideoResponse)(nil),            // 4: video.UploadVideoResponse
	(*ListVideosRequest)(nil),              // 5: video.ListVideosRequest
	(*VideoInfo)(nil),                      // 6: video.VideoInfo
	(*ListVideosResponse)(nil),             // 7: video.ListVideosResponse
	(*UpdateVideoMetadataRequest)(nil),     // 8: video.UpdateVideoMetadataRequest
	(*UpdateVideoMetadataResponse)(nil),    // 9: video.UpdateVideoMetadataResponse
	(*DeleteVideoRequest)(nil),             // 10: video.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),            // 11: video.DeleteVideoResponse
	(*PlayVideoRequest)(nil),               // 12: video.PlayVideoRequest
	(*PlayVideoResponse)(nil),              // 13: video.PlayVideoResponse
	(*GetSimilarVideosRequest)(nil),        // 14: video.GetSimilarVideosRequest
	(*GetSimilarVideosResponse)(nil),       // 15: video.GetSimilarVideosResponse
	(*GetViewCountRequest)(nil),            // 16: video.GetViewCountRequest
	(*GetViewCountResponse)(nil),           // 17: video.GetViewCountResponse
	(*ListRecommendPoolVideosRequest)(nil), // 18: video.ListRecommendPoolVideosRequest
	(*SetVideoPublishedRequest)(nil),       // 19: video.SetVideoPublishedRequest
	(*SetVideoPublishedResponse)(nil),      // 20: video.SetVideoPublishedResponse
	(*SetVideoRecommendRequest)(nil),       // 21: video.SetVideoRecommendRequest
	(*SetVideoRecommendResponse)(nil),      // 22: video.SetVideoRecommendResponse
	(*SetVideoCoverRequest)(nil),           // 23: video.SetVideoCoverRequest
	(*SetVideoCoverResponse)(nil),          // 24: video.SetVideoCoverResponse
	(*GetTranscodeStatusRequest)(nil),      // 25: video.GetTranscodeStatusRequest
	(*GetTranscodeStatusResponse)(nil),     // 26: video.GetTranscodeStatusResponse
	(*RecommendByQuestionRequest)(nil),     // 27: video.RecommendByQuestionRequest
	(*RecommendItem)(nil),                  // 28: video.RecommendItem
	(*RecommendByQuestionResponse)(nil),    // 29: video.RecommendByQuestionResponse
	(*ListRecommendationsRequest)(nil),     // 30: video.ListRecommendationsRequest
	(*ListRecommendationsResponse)(nil),    // 31: video.ListRecommendationsResponse
	(*ReportWatchRequest)(nil),             // 32: video.ReportWatchRequest
	(*ReportWatchResponse)(nil),            // 33: video.ReportWatchResponse
}
var file_video_video_service_proto_depIdxs = []int32{
	3,  // 0: video.UploadVideoRequest.meta:type_name -> video.VideoMeta
	0,  // 1: video.ListVideosRequest.filter_type:type_name -> video.VideoType
	6,  // 2: video.ListVideosResponse.videos:type_name -> video.VideoInfo
	6,  // 3: video.PlayVideoResponse.video:type_name -> video.VideoInfo
	6,  // 4: video.GetSimilarVideosResponse.videos:type_name -> video.VideoInfo
	1,  // 5: video.GetTranscodeStatusResponse.status:type_name -> video.TranscodeStatus
	6,  // 6: video.RecommendItem.video:type_name -> video.VideoInfo
	28, // 7: video.RecommendByQuestionResponse.items:type_name -> video.RecommendItem
	28, // 8: video.ListRecommendationsResponse.items:type_name -> video.RecommendItem
	2,  // 9: video.VideoService.UploadVideo:input_type -> video.UploadVideoRequest
	5,  // 10: video.VideoService.ListVideos:input_type -> video.ListVideosRequest
	8,  // 11: video.VideoService.UpdateVideoMetadata:input_type -> video.UpdateVideoMetadataRequest
	10, // 12: video.VideoService.DeleteVideo:input_type -> video.DeleteVideoRequest
	12, // 13: video.VideoService.PlayVideo:input_type -> video.PlayVideoRequest
	14, // 14: video.VideoService.GetSimilarVideos:input_type -> video.GetSimilarVideosRequest
	16, // 15: video.VideoService.GetViewCount:input_type -> video.GetViewCountRequest
	18, // 16: video.VideoService.ListRecommendPoolVideos:input_type -> video.ListRecommendPoolVideosRequest
	19, // 17: video.VideoService.SetVideoPublished:input_type -> video.SetVideoPublishedRequest
	21, // 18: video.VideoService.SetVideoRecommend:input_type -> video.SetVideoRecommendRequest
	23, // 19: video.VideoService.SetVideoCover:input_type -> video.SetVideoCoverRequest
	25, // 20: video.VideoService.GetTranscodeStatus:input_type -> video.GetTranscodeStatusRequest
	27, // 21: video.VideoService.RecommendByQuestion:input_type -> video.RecommendByQuestionRequest
	30, // 22: video.VideoService.ListRecommendations:input_type -> video.ListRecommendationsRequest
	32, // 23: video.VideoService.ReportWatch:input_type -> video.ReportWatchRequest
	4,  // 24: video.VideoService.UploadVideo:output_type -> video.UploadVideoResponse
	7,  // 25: video.VideoService.ListVideos:output_type -> video.ListVideosResponse
	9,  // 26: video.VideoService.UpdateVideoMetadata:output_type -> video.UpdateVideoMetadataResponse
	11, // 27: video.VideoService.DeleteVideo:output_type -> video.DeleteVideoResponse
	13, // 28: video.VideoService.PlayVideo:output_type -> video.PlayVideoResponse
	15, // 29: video.VideoService.GetSimilarVideos:output_type -> video.GetSimilarVideosResponse
	17, // 30: video.VideoService.GetViewCount:output_type -> video.GetViewCountResponse
	7,  // 31: video.VideoService.ListRecommendPoolVideos:output_type -> video.ListVideosResponse
	20, // 32: video.VideoService.SetVideoPublished:output_type -> video.SetVideoPublishedResponse
	22, // 33: video.VideoService.SetVideoRecommend:output_type -> video.SetVideoRecommendResponse
	24, // 34: video.VideoService.SetVideoCover:output_type -> video.SetVideoCoverResponse
	26, // 35: video.VideoService.GetTranscodeStatus:output_type -> video.GetTranscodeStatusResponse
	29, // 36: video.VideoService.RecommendByQuestion:output_type -> video.RecommendByQuestionResponse
	31, // 37: video.VideoService.ListRecommendations:output_type -> video.ListRecommendationsResponse
	33, // 38: video.VideoService.ReportWatch:output_type -> video.ReportWatchResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_video_video_service_proto_init() }
func file_video_video_service_proto_init() {
	if File_video_video_service_proto != nil {
		return
	}
	file_video_video_service_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadVideoRequest_Meta)(nil),
		(*UploadVideoRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_video_service_proto_rawDesc), len(file_video_video_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_video_service_proto_goTypes,
		DependencyIndexes: file_video_video_service_proto_depIdxs,
		EnumInfos:         file_video_video_service_proto_enumTypes,
		MessageInfos:      file_video_video_service_proto_msgTypes,
	}.Build()
	File_video_video_service_proto = out.File
	file_video_video_service_proto_goTypes = nil
	file_video_video_service_proto_depIdxs = nil
}
