// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: video/video_service.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoService_UploadVideo_FullMethodName             = "/video.VideoService/UploadVideo"
	VideoService_ListVideos_FullMethodName              = "/video.VideoService/ListVideos"
	VideoService_UpdateVideoMetadata_FullMethodName     = "/video.VideoService/UpdateVideoMetadata"
	VideoService_DeleteVideo_FullMethodName             = "/video.VideoService/DeleteVideo"
	VideoService_PlayVideo_FullMethodName               = "/video.VideoService/PlayVideo"
	VideoService_GetSimilarVideos_FullMethodName        = "/video.VideoService/GetSimilarVideos"
	VideoService_GetViewCount_FullMethodName            = "/video.VideoService/GetViewCount"
	VideoService_ListRecommendPoolVideos_FullMethodName = "/video.VideoService/ListRecommendPoolVideos"
	VideoService_SetVideoPublished_FullMethodName       = "/video.VideoService/SetVideoPublished"
	VideoService_SetVideoRecommend_FullMethodName       = "/video.VideoService/SetVideoRecommend"
	VideoService_SetVideoCover_FullMethodName           = "/video.VideoService/SetVideoCover"
	VideoService_GetTranscodeStatus_FullMethodName      = "/video.VideoService/GetTranscodeStatus"
	VideoService_RecommendByQuestion_FullMethodName     = "/video.VideoService/RecommendByQuestion"
	VideoService_ListRecommendations_FullMethodName     = "/video.VideoService/ListRecommendations"
	VideoService_ReportWatch_FullMethodName             = "/video.VideoService/ReportWatch"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 视频服务
type VideoServiceClient interface {
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadVideoRequest, UploadVideoResponse], error)
	ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosResponse, error)
	UpdateVideoMetadata(ctx context.Context, in *UpdateVideoMetadataRequest, opts ...grpc.CallOption) (*UpdateVideoMetadataResponse, error)
	DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*DeleteVideoResponse, error)
	PlayVideo(ctx context.Context, in *PlayVideoRequest, opts ...grpc.CallOption) (*PlayVideoResponse, error)
	GetSimilarVideos(ctx context.Context, in *GetSimilarVideosRequest, opts ...grpc.CallOption) (*GetSimilarVideosResponse, error)
	GetViewCount(ctx context.Context, in *GetViewCountRequest, opts ...grpc.CallOption) (*GetViewCountResponse, error)
	ListRecommendPoolVideos(ctx context.Context, in *ListRecommendPoolVideosRequest, opts ...grpc.CallOption) (*ListVideosResponse, error)
	SetVideoPublished(ctx context.Context, in *SetVideoPublishedRequest, opts ...grpc.CallOption) (*SetVideoPublishedResponse, error)
	SetVideoRecommend(ctx context.Context, in *SetVideoRecommendRequest, opts ...grpc.CallOption) (*SetVideoRecommendResponse, error)
	SetVideoCover(ctx context.Context, in *SetVideoCoverRequest, opts ...grpc.CallOption) (*SetVideoCoverResponse, error)
	GetTranscodeStatus(ctx context.Context, in *GetTranscodeStatusRequest, opts ...grpc.CallOption) (*GetTranscodeStatusResponse, error)
	RecommendByQuestion(ctx context.Context, in *RecommendByQuestionRequest, opts ...grpc.CallOption) (*RecommendByQuestionResponse, error)
	ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error)
	ReportWatch(ctx context.Context, in *ReportWatchRequest, opts ...grpc.CallOption) (*ReportWatchResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadVideoRequest, UploadVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoService_ServiceDesc.Streams[0], VideoService_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadVideoRequest, UploadVideoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoService_UploadVideoClient = grpc.ClientStreamingClient[UploadVideoRequest, UploadVideoResponse]

func (c *videoServiceClient) ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosResponse)
	err := c.cc.Invoke(ctx, VideoService_ListVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) UpdateVideoMetadata(ctx context.Context, in *UpdateVideoMetadataRequest, opts ...grpc.CallOption) (*UpdateVideoMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVideoMetadataResponse)
	err := c.cc.Invoke(ctx, VideoService_UpdateVideoMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*DeleteVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVideoResponse)
	err := c.cc.Invoke(ctx, VideoService_DeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) PlayVideo(ctx context.Context, in *PlayVideoRequest, opts ...grpc.CallOption) (*PlayVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayVideoResponse)
	err := c.cc.Invoke(ctx, VideoService_PlayVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetSimilarVideos(ctx context.Context, in *GetSimilarVideosRequest, opts ...grpc.CallOption) (*GetSimilarVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimilarVideosResponse)
	err := c.cc.Invoke(ctx, VideoService_GetSimilarVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetViewCount(ctx context.Context, in *GetViewCountRequest, opts ...grpc.CallOption) (*GetViewCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetViewCountResponse)
	err := c.cc.Invoke(ctx, VideoService_GetViewCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListRecommendPoolVideos(ctx context.Context, in *ListRecommendPoolVideosRequest, opts ...grpc.CallOption) (*ListVideosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosResponse)
	err := c.cc.Invoke(ctx, VideoService_ListRecommendPoolVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SetVideoPublished(ctx context.Context, in *SetVideoPublishedRequest, opts ...grpc.CallOption) (*SetVideoPublishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVideoPublishedResponse)
	err := c.cc.Invoke(ctx, VideoService_SetVideoPublished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SetVideoRecommend(ctx context.Context, in *SetVideoRecommendRequest, opts ...grpc.CallOption) (*SetVideoRecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVideoRecommendResponse)
	err := c.cc.Invoke(ctx, VideoService_SetVideoRecommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) SetVideoCover(ctx context.Context, in *SetVideoCoverRequest, opts ...grpc.CallOption) (*SetVideoCoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVideoCoverResponse)
	err := c.cc.Invoke(ctx, VideoService_SetVideoCover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetTranscodeStatus(ctx context.Context, in *GetTranscodeStatusRequest, opts ...grpc.CallOption) (*GetTranscodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranscodeStatusResponse)
	err := c.cc.Invoke(ctx, VideoService_GetTranscodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) RecommendByQuestion(ctx context.Context, in *RecommendByQuestionRequest, opts ...grpc.CallOption) (*RecommendByQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendByQuestionResponse)
	err := c.cc.Invoke(ctx, VideoService_RecommendByQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendationsResponse)
	err := c.cc.Invoke(ctx, VideoService_ListRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ReportWatch(ctx context.Context, in *ReportWatchRequest, opts ...grpc.CallOption) (*ReportWatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportWatchResponse)
	err := c.cc.Invoke(ctx, VideoService_ReportWatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility.
//
// 视频服务
type VideoServiceServer interface {
	UploadVideo(grpc.ClientStreamingServer[UploadVideoRequest, UploadVideoResponse]) error
	ListVideos(context.Context, *ListVideosRequest) (*ListVideosResponse, error)
	UpdateVideoMetadata(context.Context, *UpdateVideoMetadataRequest) (*UpdateVideoMetadataResponse, error)
	DeleteVideo(context.Context, *DeleteVideoRequest) (*DeleteVideoResponse, error)
	PlayVideo(context.Context, *PlayVideoRequest) (*PlayVideoResponse, error)
	GetSimilarVideos(context.Context, *GetSimilarVideosRequest) (*GetSimilarVideosResponse, error)
	GetViewCount(context.Context, *GetViewCountRequest) (*GetViewCountResponse, error)
	ListRecommendPoolVideos(context.Context, *ListRecommendPoolVideosRequest) (*ListVideosResponse, error)
	SetVideoPublished(context.Context, *SetVideoPublishedRequest) (*SetVideoPublishedResponse, error)
	SetVideoRecommend(context.Context, *SetVideoRecommendRequest) (*SetVideoRecommendResponse, error)
	SetVideoCover(context.Context, *SetVideoCoverRequest) (*SetVideoCoverResponse, error)
	GetTranscodeStatus(context.Context, *GetTranscodeStatusRequest) (*GetTranscodeStatusResponse, error)
	RecommendByQuestion(context.Context, *RecommendByQuestionRequest) (*RecommendByQuestionResponse, error)
	ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
	ReportWatch(context.Context, *ReportWatchRequest) (*ReportWatchResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServiceServer struct{}

func (UnimplementedVideoServiceServer) UploadVideo(grpc.ClientStreamingServer[UploadVideoRequest, UploadVideoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedVideoServiceServer) ListVideos(context.Context, *ListVideosRequest) (*ListVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVideos not implemented")
}
func (UnimplementedVideoServiceServer) UpdateVideoMetadata(context.Context, *UpdateVideoMetadataRequest) (*UpdateVideoMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVideoMetadata not implemented")
}
func (UnimplementedVideoServiceServer) DeleteVideo(context.Context, *DeleteVideoRequest) (*DeleteVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVideo not implemented")
}
func (UnimplementedVideoServiceServer) PlayVideo(context.Context, *PlayVideoRequest) (*PlayVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayVideo not implemented")
}
func (UnimplementedVideoServiceServer) GetSimilarVideos(context.Context, *GetSimilarVideosRequest) (*GetSimilarVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimilarVideos not implemented")
}
func (UnimplementedVideoServiceServer) GetViewCount(context.Context, *GetViewCountRequest) (*GetViewCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetViewCount not implemented")
}
func (UnimplementedVideoServiceServer) ListRecommendPoolVideos(context.Context, *ListRecommendPoolVideosRequest) (*ListVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecommendPoolVideos not implemented")
}
func (UnimplementedVideoServiceServer) SetVideoPublished(context.Context, *SetVideoPublishedRequest) (*SetVideoPublishedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVideoPublished not implemented")
}
func (UnimplementedVideoServiceServer) SetVideoRecommend(context.Context, *SetVideoRecommendRequest) (*SetVideoRecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVideoRecommend not implemented")
}
func (UnimplementedVideoServiceServer) SetVideoCover(context.Context, *SetVideoCoverRequest) (*SetVideoCoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVideoCover not implemented")
}
func (UnimplementedVideoServiceServer) GetTranscodeStatus(context.Context, *GetTranscodeStatusRequest) (*GetTranscodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranscodeStatus not implemented")
}
func (UnimplementedVideoServiceServer) RecommendByQuestion(context.Context, *RecommendByQuestionRequest) (*RecommendByQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendByQuestion not implemented")
}
func (UnimplementedVideoServiceServer) ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecommendations not implemented")
}
func (UnimplementedVideoServiceServer) ReportWatch(context.Context, *ReportWatchRequest) (*ReportWatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportWatch not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}
func (UnimplementedVideoServiceServer) testEmbeddedByValue()                      {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoServiceServer).UploadVideo(&grpc.GenericServerStream[UploadVideoRequest, UploadVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoService_UploadVideoServer = grpc.ClientStreamingServer[UploadVideoRequest, UploadVideoResponse]

func _VideoService_ListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListVideos(ctx, req.(*ListVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_UpdateVideoMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).UpdateVideoMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_UpdateVideoMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).UpdateVideoMetadata(ctx, req.(*UpdateVideoMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_DeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).DeleteVideo(ctx, req.(*DeleteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_PlayVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).PlayVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_PlayVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).PlayVideo(ctx, req.(*PlayVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetSimilarVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetSimilarVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetSimilarVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetSimilarVideos(ctx, req.(*GetSimilarVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetViewCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetViewCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetViewCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetViewCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetViewCount(ctx, req.(*GetViewCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListRecommendPoolVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendPoolVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListRecommendPoolVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListRecommendPoolVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListRecommendPoolVideos(ctx, req.(*ListRecommendPoolVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SetVideoPublished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVideoPublishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SetVideoPublished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_SetVideoPublished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SetVideoPublished(ctx, req.(*SetVideoPublishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SetVideoRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVideoRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SetVideoRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_SetVideoRecommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SetVideoRecommend(ctx, req.(*SetVideoRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_SetVideoCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVideoCoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).SetVideoCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_SetVideoCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).SetVideoCover(ctx, req.(*SetVideoCoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetTranscodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetTranscodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetTranscodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetTranscodeStatus(ctx, req.(*GetTranscodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_RecommendByQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendByQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).RecommendByQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_RecommendByQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).RecommendByQuestion(ctx, req.(*RecommendByQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListRecommendations(ctx, req.(*ListRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ReportWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ReportWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ReportWatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ReportWatch(ctx, req.(*ReportWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVideos",
			Handler:    _VideoService_ListVideos_Handler,
		},
		{
			MethodName: "UpdateVideoMetadata",
			Handler:    _VideoService_UpdateVideoMetadata_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _VideoService_DeleteVideo_Handler,
		},
		{
			MethodName: "PlayVideo",
			Handler:    _VideoService_PlayVideo_Handler,
		},
		{
			MethodName: "GetSimilarVideos",
			Handler:    _VideoService_GetSimilarVideos_Handler,
		},
		{
			MethodName: "GetViewCount",
			Handler:    _VideoService_GetViewCount_Handler,
		},
		{
			MethodName: "ListRecommendPoolVideos",
			Handler:    _VideoService_ListRecommendPoolVideos_Handler,
		},
		{
			MethodName: "SetVideoPublished",
			Handler:    _VideoService_SetVideoPublished_Handler,
		},
		{
			MethodName: "SetVideoRecommend",
			Handler:    _VideoService_SetVideoRecommend_Handler,
		},
		{
			MethodName: "SetVideoCover",
			Handler:    _VideoService_SetVideoCover_Handler,
		},
		{
			MethodName: "GetTranscodeStatus",
			Handler:    _VideoService_GetTranscodeStatus_Handler,
		},
		{
			MethodName: "RecommendByQuestion",
			Handler:    _VideoService_RecommendByQuestion_Handler,
		},
		{
			MethodName: "ListRecommendations",
			Handler:    _VideoService_ListRecommendations_Handler,
		},
		{
			MethodName: "ReportWatch",
			Handler:    _VideoService_ReportWatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _VideoService_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "video/video_service.proto",
}
